[build]
  publish = "."
  command = "echo 'No build step required for static site'"

# Handle thank you page
[[redirects]]
  from = "/thank-you"
  to = "/thank-you.html"
  status = 200

# Catch all other routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
